<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>741f2abc-bb85-4853-97e0-7e66decf3f10</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
    <PackageReference Include="MassTransit" Version="9.1.2" />
    <PackageReference Include="MassTransit.Newtonsoft" Version="9.1.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Restaurant.Contracts\Restaurant.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Restaurant.Mediator.Helper\Restaurant.Mediator.Helper.csproj" />
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
  </ItemGroup>

</Project>
