<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\services\NotificationService\NotificationService.Infrastructure\NotificationService.Infrastructure.csproj" />
    <ProjectReference Include="..\Restaurant.Application\Restaurant.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Domain\Restaurant.Domain.csproj" />
    <ProjectReference Include="..\..\shared\Restaurant.Mediator.Helper\Restaurant.Mediator.Helper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Abp" Version="10.4.0" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="MassTransit" Version="9.1.2" />
    <PackageReference Include="MassTransit.Newtonsoft" Version="9.1.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d397abd5-ae1f-449d-b40c-29dcec57aed1</UserSecretsId>
  </PropertyGroup>

</Project>
