<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Restaurant.Contracts\Restaurant.Contracts.csproj" />
    <ProjectReference Include="..\Restaurant.Domain\Restaurant.Domain.csproj" />
    <ProjectReference Include="..\..\shared\Restaurant.Mediator.Helper\Restaurant.Mediator.Helper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MassTransit.Abstractions" Version="9.1.2" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Carts\Queries\" />
    <Folder Include="Features\Review\Specifications\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
